name: nvim-notify Workflow
on: 
  - push
jobs:
  style:
    name: style
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/ tests/

  tests:
    name: tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        nvim_version:
          - v0.9.5
          - v0.10.2
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly
        uses: actions/cache@v4
        with:
          path: _neovim
          key: ${{ runner.os }}-${{ matrix.nvim_version }}-${{ hashFiles('todays-date') }}

      - name: Prepare dependencies
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            if [ "${{ matrix.nvim_version }}" = "nightly" ]; then
              curl -sL https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
            else
              curl -sL https://github.com/neovim/neovim/releases/download/${{ matrix.nvim_version }}/nvim-linux64.tar.gz | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
            fi
          }
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start

      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          ./scripts/test
          
  release:
    name: release
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - style
      - tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
